services:
  prowler:
    image: toniblyx/prowler:${PROWLER_IMAGE_TAG}
    container_name: prowler
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./prowler-output:/home/prowler/output
    command:
      - ${PROWLER_COMMAND}
    restart: unless-stopped
    expose:
      - 11666
    networks:
        - main_network

networks:
  main_network:
    external: true
